project:
  type: book
  output-dir: _book

book:
  title: "newVignettesBook"
  author: "**Mice Development Team**"
  date: last-modified
  chapters:
    - index.qmd
    - 1AdHoc/Adhoc_methods_and_mice.qmd
    - 2ConvPool/Convergence_and_pooling.qmd
    - 3Inspect/The_imputation_and_nonresponse_models.qmd
    - 4PassivePostProcess/Passive_imputation_and_Post-processing.qmd
    - 5CombInference/CombiningInferences.qmd
    - 6MultiLevel/Imputing_multilevel_data.qmd
    - 7Sensitivity/SenstivityAnalysis.qmd
    - 8FutureMice/Vignette_futuremice.qmd
    - 9Mpmm/mpmm_vignette.qmd
    - 10Synthetic/synthetic.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    toc-depth: 3
    theme: cosmo
  pdf:
    documentclass: scrreprt



